package com.fti.recyclerview;

import java.util.ArrayList;

public class MotorcycleData {
    private static String[] title = new String[]{"Kawasaki Z800", "Yamaha MT-09","Ducati Streetfighter 848", "Suzuki GSR 750","Yamaha FZ8","Benelli TNT 889 T","Ducati Monster 795 ","MV Agusta Brutale 800", "Hyosung GT650P", "Hyosung GT650R"};
    private static int[] thumbnail = new int[]{R.drawable.image1,R.drawable.image2,R.drawable.image3,R.drawable.image4,R.drawable.image5,R.drawable.image6,R.drawable.image7,R.drawable.image8,R.drawable.image9,R.drawable.image10};
    private static String[] price = new String[]{"212.000.000","250.000.000","450.000.000","199.000.000","133.350.000","277.500.000","322.000.000","385.000.000","90.000.000", "120.000.000"};

    private static String[] desc = new String[]{
            "Motor sport naked bike dengan nama Kawasaki Z800 ini memiliki mesin motor dengan kubikasi 806cc, dengan 4 cylinder segaris dengan 16 katub yang bersisitem DOHC 6-Speed dengan psistem pendingin berupa cairan (Liquid Cooled). Dengan spesifikasi mesin tersebut motor Kawasaki Z800 mampu menemburkan tenaga maksimum sebesar 113 Ps dengan putaran 10.200 rpm dengan torsi maskimunya sebesar 83 Nm pada putaran 8.000 rpm. Motor ini juga dibekali dengan sistem rangka yang kuat dan kokoh, rangka tersebut berjenis tubular backbine dan subframe. Untuk suspensi depan motor sport naked bike kawasaki Z800 ini menggunakan Upside-down fork 41 mm (KYB), sedangkan untuk baihan belakangnya menggunakan suspensi berjenis KYB shock piggyback reservoir dimana keduanya memiliki kemampuan adjustable rebound damping danprload. Dan untuk masalha harga motor sport naked bike yang satu ini memiliki harga motor mencapai 212 juta rupiah.",
            "Motor sport naked bike berikutnya ialah Yamaha MT-09, motor sport naked bike ini merupakan varian terbaru dari Yamaha yang baru saja diluncurkan beberapa waktu yang lalu. Di Eropa motor sport yang satu ini memilik nama Yamaha MT-09 atau disebut juga dengan The Darkside Of Japan, dan di Amerika motor ini disebut dengan nama yamaha FZ-09. Yamaha MT-09 ini memakai mesin motor yang berkapasitas 850cc dengan 3 siinder segaris yang dilengkapi dengan sitem DOHC 6-Speed serta memiliki sistem perndingin berupa cairan. Dengan memakai mesin tersebut motor Yamaha MT-09 ini mampu mengeluarkan tenaga maksimum sebesara 84,6 Kw dengan putaran 10.000 rpm dengan torsi maksimumnya sebesar 87,5 Nm pada putaran 8.500 rpm. Semetara itu dengan menggunakan bahan baku mesin yang lebih modern dan mengusung body yang lebih ramping, perfoma Yamaha MT-09 mampu ditunjang dengan optimal. Selain itu untuk harga motor Yamaha MT-09 ini dibanderol dengan harga sekitar 250 juta rupiah.",
            "Seperti yang kita ketahui Ducati merupakan perusahaan motor dari Itali yang sangat terkenal di dunia termasuk Indonesia. Ducati memang sangat rajin membuat dan meluncurkan varian moge-moge terbarunya dengan perfoma yang tangguh dan memiliki teknologi-teknologi yang canggih. Salah produk dari Ducati ialah Ducati Streetfighter 848, motor yang terasuk dalam kategori Motor sport naked bike 800cc ini mengusung spesifikasi mesin 849cc dengan L-Twin Cylinder, 4 Valve dengan sistem pendinginan berupa cairan (LIiquid Cooled). Dengan Menggunakan pola mesin seperti itu Ducati Streetfighter 848 ini mampu mengeluarkan tenaga maksimum sebesar 97 kW dengan putaran mesin sebesar 10.000 rpm sedangkan untuk torsi maksimumnya sebesar 93.5 Nm pada putaran 9.500 rpm. Mge ini juga dilengkapi dengan teknologi Full Injection yang akan mengefisiensikan tingkat konsumsi bahan bakar sehingga bisa menjadi lebih irit bahan bakar.",
            "Motor sport naked bike dengan harga berkisar 199 juta rupiah ini menggunakan mesin motor 4 tak dengan 4 cylinder segaris yang didukung dengan sistem DOHC 6-Speed, sehingga pembakaran dalam mesin motor Suzuki GSR 750 ini akan menjadi lebih sempurna. Selain itu mesin tersebut juga mampu menghasilkan tenaga maksimum hingga 106 hp pada putaran 10.000 rpm serta memiliki torsi maksimum sebesar 80 Nm pada putaran 9.000 rpm. Dan untuk menjaga kestabilan suhu pada mesin motor Suzuki GSR 750 ini meggunakan sistem pendinginan berupa cairan (Liquid Cooled). Untuk tampilan motor Suzuki GSR 750 ini memang terkesan garang dan lebih agresif. Barutan striping keren yang ada disetiap sudut bagian motor ini akan menjadi daya tarik tersendiri bagi motor sport naked bike dari Suzuki ini. Kemudian motor Suzuki GSR 750 ini terbilang cukup irit  karena motor suzuki GSR ini memiliki teknologi full Injection untuk sistem penyuplai bahan bakarnya.",
            "Tampil dengan gaya motor sport naked bike, motor Yamaha FZ8 ini mengusung kapasitas mesin 800cc. Motor sport Yamaha ini terbilang tangguh dan handal karena motor tersebut dibekali dengan mesin 779cc, DOHC 6-Speed dengan 4 silinser sejajar, 16 katup serta menggunakan sistem pendinginan berupa cairan. Motor Yamaha FZ8 ini mampu menyemburkan tenaga maksimum sebear 78,1 Kw dengan putaran mesin sebesar 10.000 rpm dan untuk torsi maksimumnya sebesar 82 Nm pada putaran sebesar 8.000 rpm. Dengan tenaga serta torsi sebesar itu motor Yamaha FZ8 ini mampu melakukan akselerasinya dengan cukup cepat, dan untuk menempuh jarak dari 0-200 meter saja hanya membutuhkan waktu beberapa detik saja. Apalagi motor ini telah dilengkapi dengan teknologi Full Injection sebagai sistem penyuplai bahan bakarnya sehingga motor Yamah FZ8 ini akan menjadi lebih hemat bahan bakar serta perfoma motor sport Yamaha ini menjadi lebih optimal. Di luar negri moge Yamaha FZ8 ini dibandeol dengan harga US$ 8890 atau setara dengan Rp 120 juta.",
            "Satu lagi perusahaan motor dari Itali yang menyumbangkan produk motor-motor sportnya ketahan air. Ialah Benelli perusahaan yang bergerak di bidang industri otomotif ini memang banyak meluncurkan produk motor sport naked bike ke pasar industri dalam negri. Benelli sendiri telah meluncurkan tidak kurang dari 7 varian motor sport naked bike ketanah air. Dan setiap varian moge Benelli tersebut memiliki keunggulan dan juga ketangguhan yang berbeda-beda sesuai dengan perfoma mesin yang di tunjukannya. Salah satu dari 7 produk moge andalan Benelli ialah Benelli TNT 899 T, moge ini telah dibekali dengan mesin 899cc, 4 tak dengan 3 cylinder, 12 Valve yang dilengkapi dengan sistem teknologi DOHC 6-Speed. Motor ini juga mengandalakan sistem pendingin berupa cairan (Liquid Cooled) yang akan menjaga kestabilan suhu pada mesin motor.  Memakai jenis mesin tersebut motor Benelli TNT 899 T ini mampu mengeluarka tenaga maksimum sebesar 86,5 pada putaran 10.500 rpm dengan torsi maksimum sebesar 79 Nm pada putaran 8.500 rpm.",
            "Sebagai produk new entry level, ducati monster 795 ini di bekali dengan sistem mesin yang cukup tangguh di kelas motor sport naked bike. Mengusung type mesin L-Twin Cylinder, 2 Valaves Desmodromic dengan kapasitas mensin 803cc, motor ini sanggup menghasilkan tenaga maskimum hingga 64 kW pada putarab 8.250 rpm dan untuk torsi maksimunya sebesar 78 Nm dengan putaran mesin sebasar 6.250 rpm. Motor Ducati Monster 795 ini juga dilengkapi dengan teknologi Full Injection 45 mm throttle body with steper motor. Dengan adanya teknologi tersbut bukan hanya membuat motor Ducati ini hemat bahan bakar saja namun perfoma motor Ducati Moster 795 ini menjadi lebih optimal. Untuk harga motor Ducati Monster 795 versi strandart memiliki harga yang berkisar 322 juta rupiah sedangkan untuk versi ABS memiliki harga yang lebih mahal yakni 355 juta rupiah.",
            "Motor yang satu ini merupakan motor Eropa yang memiliki perfoma yang tangguh serta memiliki sistem kenyamanan berkendara yang baik saat di kendarai. Motor yang merupakan salah satu dari 8 motor sport naked bike ini memiliki tampilan motor yang sangar dan lebih keren dibandingkan dengan motor sport naked bike lainya. Menggunakan type mesin In-Line Three, 4 tak, 12 Valve yang di lengkapi dengan sistem DOHC 6-Speed akan membuat pembakaran pada mesin motor lebih sempurna sehingga akan mengahasilkan mesin yang lebih bertenaga. Dengan menggunakan spesifikasi mesin seperti itu motor MV Agusta Brutale 800 akan mampu mengeluarkan tenaga maksimum sebesar 67,2 kW dengan putaran mesin sebesar 11.600 rpm dengan torsi maksimum sebesar 81 Nm dengan putaran 8.600 rpm. Untuk harga motor sport naked bike MV Agusta 800 memiliki harga sekitar 385 juta rupiah.",
            "Kalau kamu ingin bersenang senang dengan motor besar tetapi hanya mempunyai dana dibawah 100 juta maka kamu bisa memilih motor ini. Meski nama Hyosung GT650P belum cukup familiar ditelinga kita, pabrikan Hyosung yang berasal dari Korea ini sebenarnya sudah cukup lama berkecimpung di dunia motor roda dua Internasional. Bahkan Hyosung sudah memiliki pabrik sendiri di Indonesia, tepatnya di Semarang. \n\nTentang Hyosung GT650P, motor gede ini hadir dengan konsep naked bike untuk touring motor sport satu ini dibekali dengan mesin 650cc V-Twin DOHC 8-valve. Dengan harga yang relatif murah yakni Rp 94 juta, menjadikan motor ini sebagai motor terbaik dari segi value of money.",
            "Motor kedua yang bisa kamu miliki dengan harga masih berkisar 100 juta an adalah Hyosung GT650R. Di komunitas moge pabarikan Hyosung memang terkenal sebagai salah satu penyedia motor gede dengan harga miring di pasaran.\n\nMeski motor ini dibandrol cukup murah, tapi jangan salah. Hyosung GT650R ini sudah dibekali dengan desain full fairing yang di dalamnya terdapat mesin dengan kapasitas 647cc V-Twin DOHC 8 Valve berpendingin cairan. Mesin ini juga sudah didukung dengan sistem pembakaran bertipe injeksi.\n\nMeski vendor motor ini (Hyosung) tidak begitu terkenal di negara kita, di luar negeri sangat terkenal seperti Australia, dikarenakan mereka sudah tahu dalam pengembangan motor korea satu ini, perusahaan Suzuki punya andil."
    };

    public static ArrayList<MotorcycleModel> getListData(){
        MotorcycleModel motorcycleModel = null;
        ArrayList<MotorcycleModel> list = new ArrayList<>();
        for(int i = 0; i < title.length; i++){
            motorcycleModel = new MotorcycleModel();
            motorcycleModel.setImageMotor(thumbnail[i]);
            motorcycleModel.setNameMotor(title[i]);
            motorcycleModel.setPriceMotor(price[i]);
            motorcycleModel.setDescMotor(desc[i]);
            list.add(motorcycleModel);
        }
        return list;
    }
}
